---
- name: Manage Windows Defender or MSE via Registry
  hosts: all
  gather_facts: yes
  become: false
  vars:
    defender_action: "disable"  # Options: disable / enable
    # We can take this from servey
  tasks:

    - name: Display OS Version
      debug:
        msg: "Windows Version: {{ ansible_distribution_version }}"

    # Windows 10 or higher (Defender)
    - name: Disable Defender (Registry) on Windows 10+
      win_regedit:
        path: HKLM:\SOFTWARE\Policies\Microsoft\Windows Defender
        name: DisableAntiSpyware
        data: 1
        type: dword
      register: dis_def_win10  
      when:
        - ansible_distribution_version is version('10', '>=')
        - defender_action == "disable"

    - name: Enable Defender (Registry) on Windows 10+
      win_regedit:
        path: HKLM:\SOFTWARE\Policies\Microsoft\Windows Defender
        name: DisableAntiSpyware
        state: absent
      register: en_def_win10  
      when:
        - ansible_distribution_version is version('10', '>=')
        - defender_action == "enable"

    # Windows 10 - Disable Realtime Monitoring
    - name: Set Real-Time Protection OFF on Windows 10+
      win_regedit:
        path: HKLM:\SOFTWARE\Microsoft\Windows Defender\Real-Time Protection
        name: DisableRealtimeMonitoring
        data: 1
        type: dword
      when:
        - ansible_distribution_version is version('10', '>=')
        - defender_action == "disable"

    - name: Set Real-Time Protection ON on Windows 10+
      win_regedit:
        path: HKLM:\SOFTWARE\Microsoft\Windows Defender\Real-Time Protection
        name: DisableRealtimeMonitoring
        data: 0
        type: dword
      when:
        - ansible_distribution_version is version('10', '>=')
        - defender_action == "enable"

    # Windows 7 - MSE Real-Time Protection
    - name: Disable MSE Real-Time Protection on Windows 7
      win_regedit:
        path: HKLM:\SOFTWARE\Microsoft\Microsoft Antimalware\Real-Time Protection
        name: DisableRealtimeMonitoring
        data: 1
        type: dword
      register: dis_def_win7         
      when:
        - ansible_distribution_version is version('10', '<')
        - defender_action == "disable"

    - name: Enable MSE Real-Time Protection on Windows 7
      win_regedit:
        path: HKLM:\SOFTWARE\Microsoft\Microsoft Antimalware\Real-Time Protection
        name: DisableRealtimeMonitoring
        data: 0
        type: dword
      register: en_def_win7         
      when:
        - ansible_distribution_version is version('10', '<')
        - defender_action == "enable"

    - name: Reboot the host if required
      win_reboot:
        msg: "Rebooting after Defender registry changes"
        reboot_timeout: 600
      when: dis_def_win10.changed or en_def_win10.changed or dis_def_win7.changed or en_def_win7.changed 
          