---
- name: Enable or Disable Windows Defender on Windows Server 2022
  hosts: windows
  gather_facts: yes
  become: false

  vars:
    defender_action: "disable"  # Options: "disable" or "enable"

  tasks:

    - name: Display OS version
      debug:
        msg: "Windows Version: {{ ansible_distribution_version }}"

    - name: Disable Defender - Realtime Protection (PowerShell)
      win_shell: |
        Set-MpPreference -DisableRealtimeMonitoring $true
      when: defender_action == "disable"

    - name: Enable Defender - Realtime Protection (PowerShell)
      win_shell: |
        Set-MpPreference -DisableRealtimeMonitoring $false
      when: defender_action == "enable"

    - name: Disable Defender via Registry Policy (optional - prevents automatic re-enabling)
      win_regedit:
        path: HKLM:\SOFTWARE\Policies\Microsoft\Windows Defender
        name: DisableAntiSpyware
        data: 1
        type: dword
      when: defender_action == "disable"

    - name: Enable Defender via Registry Policy (removes the disabling key)
      win_regedit:
        path: HKLM:\SOFTWARE\Policies\Microsoft\Windows Defender
        name: DisableAntiSpyware
        state: absent
      when: defender_action == "enable"

    - name: Optional - Reboot host after Defender change
      win_reboot:
        msg: "Rebooting after Defender policy change..."
        reboot_timeout: 600
      when: defender_action == "disable"