---
- name: Set Windows Login Banner
  hosts: all
  gather_facts: true
  tasks:
    - name: Set banner caption (title) for Windows
      ansible.windows.win_regedit:
        path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System
        name: LegalNoticeCaption
        # data: "Motilal Oswal Authorized Access Only."
        data: ""
        type: String
      register: title

    - name: Set banner text (body) for Windows 
      ansible.windows.win_regedit:
        path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System
        name: LegalNoticeText
        # data: > 
        #        This is a secure system of Motilal Oswal Group.\n Unauthorized access is prohibited.
        #        This system is under the servelance and any auauthorized access will be reported.\n 
        #        Powered by Ansible Automation Platform.\n
        #        Created by Ansible.
        data : ""       
        type: String
      register: content  

    - name: Reboot the machine
      ansible.windows.win_reboot:
        reboot_timeout: 60
        #test_command: 'exit (Get-Service -Name Netlogon).Status -ne "Running"'
      when: title.changed or content.changed
      ignore_errors : true

    - name: Display the title change status
      ansible.builtin.debug:
        msg: "Banner title changed: {{ title.changed }}"

    - name: ping the windows host
      ansible.windows.win_ping:
     

#- hosts: all
#  tasks:
#   - name: check if win server is up or not
#     ansible.builtin.win_ping:
#     register: ping_status

#   - name: Display the status
#     ansible.builtin.debug:
#       msg: "{{ ping_status }}"          
