---
- name: Set Windows Login Banner
  hosts: all
  tasks:
    - name: Set banner caption (title) for Windows
      ansible.windows.win_regedit:
        path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System
        name: LegalNoticeCaption
        data: "Reserv Bank of India Authorized Access Only"
        type: String
      register: title

    - name: Set banner text (body) for Windows 
      ansible.windows.win_regedit:
        path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System
        name: LegalNoticeText
        data: "This is a secure system of Reserv Bank of India. Unauthorized access is prohibited.This system is under the servelance and any auauthorized access will be reported. Powered by Ansible Automation Platform"
        type: String
      register: content  

    - name: Reboot the machine
      ansible.windows.win_reboot:
        reboot_timeout: 120
      when: title.changed or content.changed
      ignore_errors : true

#- hosts: all
#  tasks:
#   - name: check if win server is up or not
#     ansible.builtin.win_ping:
#     register: ping_status

#   - name: Display the status
#     ansible.builtin.debug:
#       msg: "{{ ping_status }}"          