- name: Launch Google Chrome
  hosts: all
  tasks:
    - name: Use CMD to force foreground
      ansible.windows.win_shell: |
        cmd.exe /c start "" "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe"