- name: Launch Google Chrome
  hosts: all
  tasks:
    - name: Start Chrome browser
      ansible.windows.win_command: |
        Start-Process "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe"