- name: Deploy antivirus Monitoring Script
  hosts: all
  vars:
    script_name: antivirus.ps1
  tasks:
    - name: Ensure the scripts and metrics directory exists
      ansible.windows.win_file:
        path: "C:\\{{ item }}"
        state: directory
      loop: 
        - "metrics"
        - "scripts"

    - name: Copy PowerShell script to Windows
      ansible.windows.win_copy:
        src: "{{ script_name }}"
        dest: "C:\\scripts\\{{script_name}}"

#    - name: Ensure the metrics directory exists
#      ansible.windows.win_file:
#        path: C:\metrics
#        state: directory

    - name: Create a scheduled task to run daily
      community.windows.win_scheduled_task:
        name: "Antivirus Monitoring"
        description: "Check if antivirus id present and export to Prometheus"
        actions:
          - path: "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe"
            arguments: "-ExecutionPolicy Bypass -File C:\\scripts\\{{ script_name }}"
        triggers:
          - type: daily
            start_boundary: "2025-01-01T00:00:00"
            repetition:
              interval: PT1M  # Runs every 1 minute
              duration: P1D    # Ensures it repeats for the whole day
        username: "SYSTEM"
        run_level: highest
        state: present
        enabled: yes