- name: Deploy Password Age Monitoring Script
  hosts: all
  vars:
    script_name: password_age.ps1
  tasks:
    - name: Ensure the metrics directory exists
      ansible.windows.win_file:
        path: C:\metrics
        state: directory
      
    - name: Copy PowerShell script to Windows
      ansible.windows.win_copy:
        src: "{{ script_name }}"
        dest: "C:\\scripts\\{{script_name}}"

    - name: Ensure the metrics directory exists
      ansible.windows.win_file:
        path: C:\metrics
        state: directory

    - name: Create a scheduled task to run daily
      community.windows.win_scheduled_task:
        name: "Password Age Monitoring"
        description: "Check all user password ages and export to Prometheus"
        actions:
          - path: "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe"
            arguments: "-ExecutionPolicy Bypass -File C:\\scripts\\{{ script_name }}"
        triggers:
          - type: daily
            start_boundary: "2025-01-01T02:00:00"
            repetition:
              interval: PT1H  # Runs every 1 hour
              duration: P1D    # Ensures it repeats for the whole day
        username: "SYSTEM"
        state: present
        enabled: yes