---
- name: Disable_Enable USB ports on Windows Operating system
  hosts: all
  gather_facts: true
  tasks:
    - name: Check if server are reachable or not
      ansible.windows.win_ping:
      register: ping_result
      
    - debug:
        msg: "{{ ping_result }}"   
          
    - name: Disable USB storage devices
      win_regedit:
        path: HKLM:\SYSTEM\CurrentControlSet\Services\USBSTOR
        name: Start
        data: 4
        type: dword
        state: present
      when:  
        - usb_disable|default(true)|bool == true

    - name: Enable USB storage devices
      win_regedit:
        path: HKLM:\SYSTEM\CurrentControlSet\Services\USBSTOR
        name: Start
        data: 3
        type: dword
        state: present
      when:  
        - usb_disable|default(true)|bool == false                
