---
- name: Disable_Enable USB ports on Windows Operating system
  hosts: all
  gather_facts: true
  tasks:
    - name: Check if server are reachable or not
      ansible.windows.win_ping:
      register: ping_result

   # - debug:
   #     msg: "{{ ping_result }}"

    - name: Disable USB storage devices
      win_regedit:
        path: HKLM:\SYSTEM\CurrentControlSet\Services\USBSTOR
        name: Start
        data: 4
        type: dword
        state: present
      register: usb_dis
      when:
        - usb_disable|default(true)|bool == true

    - name: Enable USB storage devices
      register: usb_en
      win_regedit:
        path: HKLM:\SYSTEM\CurrentControlSet\Services\USBSTOR
        name: Start
        data: 3
        type: dword
        state: present
      when:
        - usb_disable|default(true)|bool == false

    - name: Reboot system after whitelisting USB device (if required)
      win_reboot:
        reboot_timeout: 120
      ignore_errors : true  
      when: usb_en.changed or usb_dis.changed