---
- name: Disable_Enable USB ports on Windows Operating system
  hosts: all
  gather_facts: true
    #  runas: true  
  vars:
    usb_allow_list:
       - 'USB\ROOT_HUB30\4&2B8754FF&0&0'  
    # Replace with actual Hardware ID
  tasks:
    - name: Check if server are reachable or not
      ansible.windows.win_ping:
      register: ping_result

   # - debug:
   #     msg: "{{ ping_result }}"

    - name: Disable USB storage devices
      win_regedit:
        path: HKLM:\SYSTEM\CurrentControlSet\Services\USBSTOR
        name: Start
        data: 4
        type: dword
        state: present
      register: usb_dis
      when:
        - usb_disable|default(true)|bool == true

    - name: Enable USB storage devices
      register: usb_en
      win_regedit:
        path: HKLM:\SYSTEM\CurrentControlSet\Services\USBSTOR
        name: Start
        data: 3
        type: dword
        state: present
      when:
        - usb_disable|default(true)|bool == false

    - name: Enable USB storage devices for specific device IDs (Modify with actual device ID)
      win_regedit:
        path: HKLM:\SYSTEM\CurrentControlSet\Enum\USB\USB\VID_346D&PID_5678\5861741057040343248\Device Parameters
        name: Start
        data: 3
        type: dword
        state: present

    - ansible.builtin.debug:
        msg: "{{ usb_en }} {{usb_dis}}"
    - name: Reboot system after whitelisting USB device (if required)
      win_reboot:
        reboot_timeout: 120
      when: usb_en.changed or usb_dis.changed