---
- name: Set up NTP server on RHEL 9 using Chrony
  hosts: all
  become: yes
  tasks:

    - name: Install chrony package
      yum:
        name: chrony
        state: present

    - name: Configure chrony as an NTP server
      copy:
        dest: /etc/chrony.conf
        content: |
          # Use the default CentOS pool servers
          pool 2.centos.pool.ntp.org iburst

          # Allow NTP client access from the local network
          allow 192.168.1.0/24

          # Serve time even if not synchronized to any NTP server
          local stratum 10

          # Specify log file
          logdir /var/log/chrony

          # Dump measurements when chronyd exits
          dumpdir /var/lib/chrony

          # Save drift file
          driftfile /var/lib/chrony/drift

      notify:
        - restart chronyd

    - name: Enable and start chronyd service
      systemd:
        name: chronyd
        enabled: yes
        state: started

  handlers:
    - name: restart chronyd
      systemd:
        name: chronyd
        state: restarted