---
- name: Configure NTP server on Windows and synchronize time
  hosts:  all
  #become: yes
  force_handlers: True
  gather_facts: false
  tasks:

   # - name: Install NTP service
   #   win_feature:
   #     name: NTP
   #     state: present

##This step is not necessary but added for asthetics so ip is not shown but fqdn looks more appling 
    - name: Configure NTP server on windows host
      copy:
        dest: C:\Windows\System32\drivers\etc\hosts
        content: |
          192.168.20.115   rhel.ntpserver.local
     # notify:
     #   - restart ntpd

    - name: Synchronize time with NTP server
      ansible.windows.win_powershell: 
        script: |
          w32tm /config /manualpeerlist:"rhel.ntpserver.local" /syncfromflags:manual /reliable:YES
          w32tm /resync
      notify:
        - restart w32time
      ignore_errors: true  

  handlers:
   # - name: restart ntpd
   #   win_service:
   #     name: ntpd
   #     state: restarted

    - name: restart w32time
      win_service:
        name: w32time
        state: restarted
