---
- name: Set up NTP server on RHEL 9 using Chrony
  hosts: all
  become: yes
  tasks:
    - name: check if chrony is installed
      shell: rpm -qa | grep chrony
      register: chrony_installed
      ignore_errors: True
      check_mode: False
      changed_when: False

    - name: print
      debug:
        msg: "chrony is installed"
      when: chrony_installed.rc == 0
      
    - name: Install chrony package
      yum:
        name: chrony
        state: present
      when: chrony_installed.rc != 0  

    - name: Configure chrony as an NTP server
      copy:
        dest: /etc/chrony.conf
        content: |
          # Use the default CentOS pool servers
          pool 2.centos.pool.ntp.org iburst

          # Allow NTP client access from the local network
          allow 192.168.1.0/16
          allow 192.168.20.0/24
          allow 192.168.0.0/24
          #Allow NTP client to access from local network hostonly
          allow 192.168.56.0/24
          allow 192.168.64.0/24
          # Serve time even if not synchronized to any NTP server
          local stratum 10

          # Specify log file
          logdir /var/log/chrony

          # Dump measurements when chronyd exits
          dumpdir /var/lib/chrony

          # Save drift file
          driftfile /var/lib/chrony/drift

      notify:
        - restart chronyd

    - name: Enable and start chronyd service
      systemd:
        name: chronyd
        enabled: yes
        state: started

    - name: Ensure firewalld is running
      ansible.builtin.service:
        name: firewalld
        state: started
        enabled: yes

    - name: Open UDP port 123 for NTP (Chrony) on the server
      ansible.posix.firewalld:
        port: "{{ item }}/udp"
        permanent: true
        state: enabled
        immediate: true
      loop:
        - 123
        - 323
      notify:
        - Reload firewalld  
  
  handlers:
    - name: restart chronyd
      systemd:
        name: chronyd
        state: restarted

    - name: Reload firewalld
      ansible.builtin.service:
        name: firewalld
        state: reloaded        