---
- name: Disable USB storage and enable one USB port on Windows 7
  hosts: all
  tasks:
    
    # Task 1: Disable USB storage via Registry
    - name: Disable USB storage by modifying registry
      ansible.windows.win_regedit:
        path: 'HKLM:\SYSTEM\CurrentControlSet\Services\USBSTOR'
        name: 'Start'
        data: 4
        type: dword
     # become: yes
    
    # Task 2: Ensure DevCon is available on the machine
    - name: List all USB devices
      ansible.windows.win_shell: |
        Get-WmiObject Win32_PnPEntity | Where-Object { $_.Description -like "*USB*" } | Select-Object DeviceID, Description
      register: usb_devices

    - name: Show USB devices
      debug:
        var: usb_devices.stdout_lines