---
- name: start a command prompt
  hosts: all
  gather_facts: false
  tasks:
#      - name: Run a cmd.exe command
    - name: Run regedit.exe locally (on target node) as SYSTEM and interactively
      community.windows.win_psexec:
        command: cmd.exe
        interactive: true
        #system: true