---
- name: start a command prompt
  hosts: all
  gather_facts: true
  tasks:
      - name: Run a cmd.exe command
        community.windows.psexec:
          hostname: "192.168.1.13"
          connection_username: nrathi
          connection_password: primod123
          executable: cmd.exe
          arguments: /c echo Hello World