- name: Install & Configure Windows Exporter for USB Monitoring
  hosts: windows
  tasks:

    - name: Create Directory if it does not exist
      ansible.builtin.win_file:
        path: "C:\\Temp"
        state: directory
  block:
    - name: 'Download the Windows Exporter package to a local folder'
      become: false
      ansible.builtin.get_url:
        url: 'https://github.com/prometheus-community/windows_exporter/releases/latest/download/windows_exporter-0.22.0-amd64.msi'
        dest: '/tmp/windows_exporter-0.22.0-amd64.msi'
        #checksum: 'sha256:{{ windows_exporter_checksum_url }}'
        mode: 0644
      delegate_to: localhost
      check_mode: false

    - name: 'Copy the Windows Exporter package to a target host'
      ansible.windows.win_copy:
        src: '/tmp/windows_exporter-0.22.0-amd64.msi'
        dest: 'C:\\Temp\\windows_exporter.msi'
      check_mode: false

    #- name: Download Windows Exporter
    #  ansible.builtin.win_get_url:
    #    url: "https://github.com/prometheus-community/windows_exporter/releases/latest/download/windows_exporter-0.22.0-amd64.msi"
    #    dest: "C:\\Temp\\windows_exporter.msi"

    - name: Install Windows Exporter
      ansible.builtin.win_package:
        path: "C:\\Temp\\windows_exporter.msi"
        arguments: "/quiet /norestart"
        state: present

    - name: Enable USB Monitoring
      community.windows.win_lineinfile:
        path: "C:\\Program Files\\windows_exporter\\windows_exporter.yaml"
        line: "  enabled: cpu, memory, logical_disk, usb"
        insertafter: "collectors:"
        state: present

    - name: Restart Windows Exporter Service
      ansible.builtin.win_service:
        name: "windows_exporter"
        state: restarted