---
- name: 'Setup the Windows Exporter'
  hosts: all
  roles:
    - role: antmelekhin.windows_exporter
      windows_exporter_collectors_enabled: '[defaults],memory'
      __windows_exporter_architecture_dict:
        - 32-bit: '386'
        - 64-bit: 'arm64'
      windows_exporter_collectors:
        - name: service
          flags:
            services-where: Name='windows_exporter'