---
- name: Install Datadog Agent on Windows
  hosts: windows_hosts
  vars:
    datadog_api_key: "YOUR_DATADOG_API_KEY"
    datadog_site: "datadoghq.com"
  tasks:
    - name: Install Datadog Agent
      include_role:
        name: datadog.dd.datadog_agent