---
- name: Respond to webhook POST
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  rules:
    - name: R1 - Disable USB device
      condition: event.payload.action is defined and event.payload.action == "disallow usb storage"
      action:
        run_job_template:
          name: '01-js-usb'
          organization: 'Default'
          job_args:
            limit: "{{ event.payload.deviceIp }}"          
            extra_vars:
              usb_disable: true

    - name: R2 - Enable USB device
      condition: event.payload.action is defined and event.payload.action == "allow usb storage"
      action:
        run_job_template:
          name: '01-js-usb'
          organization: 'Default'
          job_args:
            limit: "{{ event.payload.deviceIp }}"
            extra_vars:
              usb_disable: false

    - name: R3 - Send Notifucation"
      condition: event.payload.action is defined and event.payload.action == "Rotate password"
      action:
        run_job_template:
          name: '01-js-user-notification'
          organization: 'Default'
          job_args:
            extra_vars:
              hosts: "{{ event.payload.deviceIp }}"

    - name: R4 - Setup Banner"
      condition: event.payload.action is defined and event.payload.action == "setup banner"
      action:
        run_job_template:
          name: '01-js-banner'
          organization: 'Default'

    - name: R5 - Sync Time"
      condition: event.payload.action is defined and event.payload.action == "sync time"
      action:
        run_job_template:
          name: '01-js-ntp-client'
          organization: 'Default'