---
- name: Respond to webhook POST
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  rules:
    - name: R1 - Disable USB device
      condition: event.payload.action is defined and event.payload.action == "disallow usb storage"
      action:
        run_job_template:
          name: 'eda - site down'
          organization: 'Default'
          job_args:
            extra_vars:
              message: from eda
              sleep: 1

    - name: R2 - Enable USB device
      condition: event.payload.action is defined and event.payload.action == "allow usb storage"
      action:
        run_job_template:
          name: 'eda - site down'
          organization: 'Default'
          job_args:
            extra_vars:
              message: from eda
              sleep: 1
              
    - name: R3 - Send Notifucation"
      condition: event.payload.action is defined and event.payload.action == "Rotate password"
      action:
        run_job_template:
          name: 'eda - site down'
          organization: 'Default'
          job_args:
            extra_vars:
              message: from eda
              sleep: 1                   